language: python
python:
- 3.4
- 3.5
- 3.6
before_install:
    -bash ecr_credentials.sh
install:
- pip install .
- pip install -r requirements.txt
- pip install --user awscli
before_script: export PYTHONPATH=$PYTHONPATH:$(pwd)
script:
- bash lambda_deploy.sh
true:
  branch: dev
env:
  global:
  - secure: WazFdG9OdKY2MU/4KXbjS8adFSbdxsji27C5M41cSIVBfcEUrOvManMhOP6VpykdHcUXg/IYPTMqGs33dUXq+abZ0fxARdAZjpfAAY8lx95vKMmQxsgoqExWTzjZoXC+uEYSGy9gnSJs03sFkwmz0dfB/FLqXrgHa00oucQqFSzdruJW0Tsnq0kw1uVwFSUItfztsoEwrxQAsyy+pAW9Gs3pLVeUVzKDPXd/YVc1bOuufuMSw5nUQaeI6Ah8IAxQom5uws1X9QfDMRbIiaY2FHInusJP9bQPlVfiqzhHsLNLM1L4z7/3EIuI9zLJj3b9MJCmyuTsWQ4FRkeQ8ZZYDPHw/B2DlSDMXK1xfHfPZYPDBNxdq//dDJwB7rmWjB1fftNpZEqf4GvErT4iAj/hEezAyFT9A4aLO8BqqcSanahBT8nxWDykTM3DjYEEXCFoqZnoAMHYZ1dUZfPfKI7qTJHm00YZ/XyClto9FsFz8GvyVvSB9v3BUi/K8lMT8TY5+ejKFSKomC3JS5DhKB0Pnig/y+sjRN8BzDZA1DrbiyFwrgYXjw5GKNwAq1luPJ397BapIMI52QY469NrjRhtvGc+KSapJm7BZPIWB3TTs4yLDy8BvTcLd9JPp1Nd1bBuwxQ5dC/7un8xM7lzKYvmZNNF2YZynsl23mEg+cuPyxw=
  - secure: KS/2FcbZg57BVX+iyVfaZIkWoxyO0cg3qOiYJccRc9oKVS7mBfnZ0KRgetfBrNl86CeGa+DEIdywrTZWle1Bfc38N9MgZuzYe831q/JlABcKgH7EC7XMM0PBq/d3rus4p73i4mcvvyq3Q8XZSI/7GitjteUZ9ILL+a/YmOtJEcdyy1wUz6ncRTJOVzWZfclOM+LDJijQritVJmCFCqKacuRGLRdbVE0AZ4RWJUdworXTghzRt9q+Eoi5E4CNg6QQkUi0d403YTX4kJWiIa/yXBEE6UjhdXLQXwuRJj/0sjLzIcYQ3mElRmKNkrVzKf/jA6iHqLVYBTHymXfkY7Cfz1AhNTo7DPctd9HMy5JQIu4aXQ0Maj0IOUqIUUJJ3Pj2+m7tQA3LSk0iUnIVsUit6n0zW/Tfh2ztpT0y0UTejZsXYcstk7nABX/5AqdUKkBCwbffjLXwyDozZ1Y+cMcyRvhjWEYv1HTALo1CRoYVoDkAtd8h3RY79K40yBcpHy5WqJfVAXscng1FVVC/TlmYXg0H0A486NoJ5JixvWYZfqtQXgYXxvEKrp6a09MKe6fCHdCZQ4mGl5t0k45jjgKrXcaGXX4OoAlQyhlY+6f4r1FPOO2UxpLqjlfNlDXZqbD7Yk5LuzGrnCSfOH5XMnP3iadetSdU8iqEG0BDYeW1SaI=
